## Point 3.1

In [1]:
%matplotlib inline
import math
import pandas as pd
import numpy as np
import matplotlib

In [2]:
a = np.array([[[1, 2] , [4, 5 ], [7, 8], [7, 8]], [[1, 2] , [4, 5 ], [7, 8], [7, 8]],  [[1, 2] , [4, 5 ], [7, 8], [7, 8]]])

In [3]:
a

array([[[1, 2],
        [4, 5],
        [7, 8],
        [7, 8]],

       [[1, 2],
        [4, 5],
        [7, 8],
        [7, 8]],

       [[1, 2],
        [4, 5],
        [7, 8],
        [7, 8]]])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[0, :, :] #first matrix

array([[1, 2],
       [4, 5],
       [7, 8],
       [7, 8]])

In [6]:
a [0, 0, 0] #first matrix, first string

1

In [7]:
 a [0, 0, :] # #first matrix, first string

array([1, 2])

## Point 3.2

In [8]:
%%time
a = np.array([x for x in range (1, 10000000)])

Wall time: 3.42 s


In [9]:
%%time
a.sum()

Wall time: 0 ns


-2014260032

In [10]:
type(a)

numpy.ndarray

In [11]:
%%time
b = [x for x in range (1, 10000000)]

Wall time: 1.25 s


In [12]:
%%time
sum (b)

Wall time: 746 ms


49999995000000L

## Point 3.3

In [13]:
%%time
np.linspace(13.0, 25.0, 15000000)

Wall time: 73 ms


array([ 13.       ,  13.0000008,  13.0000016, ...,  24.9999984,
        24.9999992,  25.       ])

In [14]:
def linspac(beg, end, nos):
    a = [beg + i*(end-beg)/(nos-1) for i in range(0, nos)]
    return a

In [15]:
%%time
linspac(13.0, 25.0, 15000000)

Wall time: 4.46 s


[13.0,
 13.000000800000054,
 13.000001600000108,
 13.00000240000016,
 13.000003200000213,
 13.000004000000267,
 13.00000480000032,
 13.000005600000373,
 13.000006400000427,
 13.00000720000048,
 13.000008000000534,
 13.000008800000586,
 13.00000960000064,
 13.000010400000694,
 13.000011200000747,
 13.0000120000008,
 13.000012800000853,
 13.000013600000907,
 13.00001440000096,
 13.000015200001013,
 13.000016000001066,
 13.00001680000112,
 13.000017600001174,
 13.000018400001228,
 13.00001920000128,
 13.000020000001333,
 13.000020800001387,
 13.00002160000144,
 13.000022400001493,
 13.000023200001547,
 13.0000240000016,
 13.000024800001654,
 13.000025600001706,
 13.00002640000176,
 13.000027200001814,
 13.000028000001867,
 13.00002880000192,
 13.000029600001973,
 13.000030400002027,
 13.00003120000208,
 13.000032000002133,
 13.000032800002186,
 13.00003360000224,
 13.000034400002294,
 13.000035200002346,
 13.0000360000024,
 13.000036800002453,
 13.000037600002507,
 13.00003840000256,
 13.